### ISSUE TITLE
Break from rlindsgaard

### ISSUE THREAD

**Issue by lakruzz** [Praqma/pretested-integration-plugin#2]
[JENKINS-32335](https://issues.jenkins-ci.org/browse/JENKINS-32335)
[Trello card](https://trello.com/c/B4KsvGhp/64-jenkins-32335-break-fork-from-rlindsgaard)

---

For some reason our repository is stil a fork from rlindsgaard/pretested-integration-plugin.

It shouldn't be, the forked repo is unsearchable and we don't have a relation to the repo any more.

It seems like this can not be done by ourselves - we will have to contact GitHub staff:

https://github.com/brianmhunt/casper-chai/issues/10

- [x] Break Praqma's fork
- [ ] make jenkinsci's repo a fork of Praqma's (not team-delta's)

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/13070426/b96b324c-d48c-11e5-9e87-71ca844c4bb4.png)

**Comment by lakruzz** [comment]
@buep 
>Further the https://github.com/jenkinsci/pretested-integration-plugin should be a fork of Praqmas repo, not the pcds2013-team-delta repo.

>All our plugin is originated from Praqmas Github account, and then forked to jenkinsci.

**Comment by lakruzz** [comment]
@praqma-thi 
>Just sent git support a mail and they did it the same day.

**Comment by lakruzz** [comment]
@buep 
>We try to break the jenkinsci fork also... so still in progress.

>Normally Jenkinsci is a fork from praqma's repo, to ensure we have full control our the code that goes in (also for security reasons).

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/13070598/0fc5ee74-d48e-11e5-9fce-737bd18e7d0d.png)
 We still need to fix this right!

@buep, @praqma-thi Did you flag this to GitHub support?

**Comment by lakruzz** [comment]
@praqma-thi Could you update status on this issue?

**Comment by praqma-thi** [comment]
Our fork's link is fixed, but the jenkinsci repository is still pointing to the code camp one.
I contacted GitHub support to fix that one as well, but they need an owner from the jenkinsci organization to request it before they do it.

Someone suggested Daniel Beck but I haven't reached out to him yet.
Had to dig around a bit to find contact information: dbeck@cloudbees.com

**Comment by praqma-thi** [comment]
Mailed him during some downtime.

**Comment by praqma-thi** [comment]
"Hi Thierry,

No problem, I'd be happy to. I'm out sick this week and possibly the next, but I'll add it to the list of things to do once back. If you haven't heard from me in two weeks, please poke me again."

**Comment by praqma-thi** [comment]
He mailed me to say he mailed GH support.

**Comment by lakruzz** [comment]
All right - just keen an eye on this - it's still hanging:

![image](https://cloud.githubusercontent.com/assets/155492/13253011/0d8275fe-da3a-11e5-87de-8f6ef8d59f85.png)
@praqma-thi @daniel-beck

**Comment by praqma-thi** [comment]
He got a mail back, they were asking for a Praqma owner next, just sent a mail to let them know I'm actually one, so it should probably be resolved by tomorrow.

**Comment by praqma-thi** [comment]
![selection_010](https://cloud.githubusercontent.com/assets/12794699/13277839/13eea948-dacc-11e5-91ef-0cd775557988.png)

**Comment by lakruzz** [comment]
Hurray!!!
